### ISSUE TITLE
Hello_World | busyhe

### ISSUE THREAD

**Issue by busyhe** [busyhe/busyhe.github.io#1]
http://blog.busyhe.cn/2019/04/08/Hello_World/ 

 又重新把博客给弄了一下，从了解Hexo + github + nginx技术到现在，期间整理了好多次。有时候看到有新的技术练个手、看到好看的主题重新把博客弄下，到后面都是把博客给遗弃到一边。现在估计年龄大了，老了。从一开始的兴（zhuang）趣（bi），到现在的生活的沉淀。不管在技术方面还是生活方面，总想留下些脚印。以后回看还是感觉美好的。

**Comment by BusyHe** [comment]
测试评论功能
